import type { Rng } from '../core/rng';
import { DROP_ODDS, HEAL_ORB_SHARE } from './balance';

export type DropKind = 'currency' | 'heal';

export interface DropDef {
  id: DropKind;
  /** Generated by BootScene until real art replaces it. */
  texture: string;
}

export const DROPS: readonly DropDef[] = [
  { id: 'currency', texture: 'drop-currency' },
  { id: 'heal', texture: 'drop-heal' },
];

/** Carried across floors so a dry streak doesn't reset on the stairs. */
export interface DropLuck {
  /** Kills in a row without a heal orb. */
  healMisses: number;
}

export const FRESH_LUCK: DropLuck = { healMisses: 0 };

/** Heal orb odds grow with each kill that didn't drop one; items add `bonus`, which can be negative. */
export function healChance(luck: DropLuck, bonus = 0): number {
  return Math.max(0, Math.min(1, DROP_ODDS.heal + bonus + DROP_ODDS.healPerMiss * luck.healMisses));
}

/** The part of a run a pickup can change. */
export interface PickupState {
  health: number;
  maxHealth: number;
  currency: number;
}

/** A floor boss always leaves at least one heal orb; one that drops resets the dry streak like any other. */
export function withBossHeal(drops: readonly DropKind[], luck: DropLuck): { drops: DropKind[]; luck: DropLuck } {
  if (drops.includes('heal')) return { drops: [...drops], luck };
  return { drops: [...drops, 'heal'], luck: FRESH_LUCK };
}

/** A heal orb waits on the floor while HP is full, for when it's needed; anything else is always taken. */
export function canCollect(kind: DropKind, healthFull: boolean): boolean {
  return kind !== 'heal' || !healthFull;
}

/** HP one heal orb restores: a share of max HP, so it scales with HP items. */
export function healOrbHp(maxHealth: number): number {
  return Math.ceil(maxHealth * HEAL_ORB_SHARE);
}

/** State after picking up one drop, each coin worth `coinValue`. Healing never passes max HP. */
export function applyDrop(state: PickupState, kind: DropKind, coinValue = 1): PickupState {
  if (kind === 'currency') return { ...state, currency: state.currency + coinValue };
  return { ...state, health: Math.min(state.maxHealth, state.health + healOrbHp(state.maxHealth)) };
}

/** What one kill drops, and the luck after it; `coins` false for an enemy that never pays out coins. */
export function rollDrops(
  rng: Rng,
  luck: DropLuck,
  healBonus = 0,
  coins = true,
): { drops: DropKind[]; luck: DropLuck } {
  const drops: DropKind[] = [];
  // Rolled either way, so the heal roll after it draws the same number.
  if (rng.chance(DROP_ODDS.currency) && coins) drops.push('currency');
  if (!rng.chance(healChance(luck, healBonus))) return { drops, luck: { healMisses: luck.healMisses + 1 } };
  drops.push('heal');
  return { drops, luck: FRESH_LUCK };
}
