import type { Rng } from '../core/rng';
import type { MessageKey } from '../i18n';
import { pickWeighted } from './itemPool';

/** Stops, swells for `telegraphMs`, then lunges at where the player stood when the telegraph began. */
export interface DashAttack {
  kind: 'dash';
  /** Measured from the start of the previous dash. */
  everyMs: number;
  telegraphMs: number;
  durationMs: number;
  speed: number;
  /** Only dashes at a target this close; farther off, the dash waits and the volley takes over. */
  maxDistance?: number;
}

/**
 * Punishes keeping away: once the player has stayed beyond `minDistance` for `farMs` straight,
 * the enemy stops with glowing eyes for `telegraphMs`, then fires a fan of slow orbs.
 */
export interface VolleyAttack {
  kind: 'volley';
  minDistance: number;
  farMs: number;
  /** 0 fires on the move, with no stop and no eye glow. */
  telegraphMs: number;
  /** Measured from the shot. */
  cooldownMs: number;
  count: number;
  /** Total fan angle in degrees. */
  spreadDeg: number;
  speed: number;
  damage: number;
}

/** Stops and swells for `telegraphMs`, then calls in plain enemies of `minionId` around itself. */
export interface SummonAttack {
  kind: 'summon';
  /** Measured from the start of the previous summon. */
  everyMs: number;
  telegraphMs: number;
  min: number;
  max: number;
  /** Skips the summon while this many enemies are already up, so a long fight doesn't flood the room. */
  maxAlive: number;
  minionId: string;
}

export type EnemyAttack = DashAttack | VolleyAttack | SummonAttack;

/**
 * A harder second phase. Past the HP threshold the enemy turns invulnerable for the
 * transition, then trades its normal dash for a furious one that ricochets off walls.
 */
export interface FuryPhase {
  /** Starts once HP drops below this share of the max. */
  hpShare: number;
  transitionMs: number;
  /** Added to the body's colors: the shadow is near black, so a multiplied tint wouldn't show. */
  tint: number;
  dash: FuryDash;
}

/** Launched without stopping, after a short eye flash; the direction locks when the flash starts. */
export interface FuryDash {
  /** Measured from the start of the previous dash. */
  everyMs: number;
  flashMs: number;
  speed: number;
  /** Total path length, bounces included. */
  distance: number;
  damage: number;
}

export interface EnemyDef {
  id: string;
  name: MessageKey;
  /** Generated by BootScene until real art replaces it. */
  texture: string;
  hp: number;
  /** Share of base HP added per floor after the first. */
  hpGrowth: number;
  speed: number;
  scale: number;
  /** HP the player loses on touch. */
  contactDamage: number;
  /** Bosses ignore knockback. */
  boss: boolean;
  /** A room event's mini boss: ignores knockback and shows the boss HP bar, but isn't a floor boss. */
  miniBoss?: boolean;
  attacks: readonly EnemyAttack[];
  fury?: FuryPhase;
  /** Color of a silhouette drawn around the body; cursed enemies get one. */
  outline?: number;
  /** Stronger, and its drops are rolled twice. */
  cursed?: boolean;
  deathColor: number;
}

export const SHADOW: EnemyDef = {
  id: 'shadow',
  name: 'enemy.shadow',
  texture: 'shadow',
  hp: 12,
  hpGrowth: 0.15,
  speed: 115,
  scale: 1,
  contactDamage: 10,
  boss: false,
  attacks: [],
  deathColor: 0x2a2144,
};

/** Keeps back and shoots single orbs; slower and frailer than a plain shadow. */
export const SHADOW_CASTER: EnemyDef = {
  id: 'shadow-caster',
  name: 'enemy.shadow-caster',
  texture: 'shadow-caster',
  hp: 9,
  hpGrowth: 0.15,
  speed: 70,
  scale: 1,
  contactDamage: 10,
  boss: false,
  attacks: [
    {
      kind: 'volley',
      minDistance: 120,
      farMs: 1200,
      // No tell: the player has to keep an eye on it.
      telegraphMs: 0,
      cooldownMs: 2600,
      count: 1,
      spreadDeg: 0,
      speed: 150,
      damage: 10,
    },
  ],
  deathColor: 0x3a1f4a,
};

/** The Colossus dashes at players within this distance and shoots at those beyond it. */
const COLOSSUS_REACH = 260;

export const SHADOW_COLOSSUS: EnemyDef = {
  id: 'shadow-colossus',
  name: 'boss.shadow-colossus',
  texture: 'shadow',
  hp: 150,
  hpGrowth: 0.2,
  speed: 70,
  scale: 2.4,
  contactDamage: 10,
  boss: true,
  attacks: [
    { kind: 'dash', everyMs: 2000, telegraphMs: 380, durationMs: 420, speed: 460, maxDistance: COLOSSUS_REACH },
    {
      kind: 'volley',
      minDistance: COLOSSUS_REACH,
      farMs: 700,
      telegraphMs: 500,
      cooldownMs: 3000,
      count: 3,
      spreadDeg: 36,
      speed: 170,
      damage: 10,
    },
  ],
  fury: {
    hpShare: 0.4,
    transitionMs: 600,
    tint: 0x360808,
    // 40% farther than the normal dash (460 px/s for 420 ms).
    dash: { everyMs: 2400, flashMs: 150, speed: 520, distance: 270, damage: 15 },
  },
  deathColor: 0x2a2144,
};

export const ENEMIES: readonly EnemyDef[] = [SHADOW, SHADOW_CASTER, SHADOW_COLOSSUS];

/** Who can fill a normal room, how often, and from which floor on. */
export interface RoomEnemy {
  def: EnemyDef;
  weight: number;
  minDepth: number;
}

export const ROOM_ENEMIES: readonly RoomEnemy[] = [
  { def: SHADOW, weight: 3, minDepth: 1 },
  // Floor 1 stays melee only while the player learns to move and shoot.
  { def: SHADOW_CASTER, weight: 1, minDepth: 2 },
];

/** `count` enemy kinds for a room on floor `depth`, each rolled by weight among those allowed there. */
export function rollRoomEnemies(
  rng: Rng,
  depth: number,
  count: number,
  table: readonly RoomEnemy[] = ROOM_ENEMIES,
): EnemyDef[] {
  const allowed = table.filter((e) => depth >= e.minDepth);
  if (allowed.length === 0) return [];
  return Array.from({ length: count }, () => pickWeighted(rng, allowed).def);
}

/** Floor 1 uses the base HP; each floor after adds a fixed share of it. */
export function enemyForDepth(def: EnemyDef, depth: number): EnemyDef {
  const floorsAfterFirst = Math.max(0, depth - 1);
  return { ...def, hp: Math.round(def.hp * (1 + def.hpGrowth * floorsAfterFirst)) };
}

/** True when a hit takes HP from above the fury threshold to below it. */
export function crossesFury(def: EnemyDef, hpBefore: number, hpAfter: number): boolean {
  if (!def.fury) return false;
  const threshold = def.hp * def.fury.hpShare;
  return hpBefore >= threshold && hpAfter < threshold;
}

export function findAttack<K extends EnemyAttack['kind']>(
  def: EnemyDef,
  kind: K,
): Extract<EnemyAttack, { kind: K }> | undefined {
  return def.attacks.find((a): a is Extract<EnemyAttack, { kind: K }> => a.kind === kind);
}
